joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 1000

joint_group_pos_controller:
    type: position_controllers/JointGroupPositionController
    joints: 
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
